FROM node:24-slim
WORKDIR /app

COPY package.json tsconfig.json vite.config.ts ./
RUN npm install && chown -R node:node /app

USER node

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
