services:
  gabarito-frontend:
    container_name: gabarito-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/app/dist-out
    entrypoint: sh -c "mkdir -p /app/dist-out && rm -rf /app/dist-out/* && cp -rf /usr/share/nginx/html/. /app/dist-out/ && exec nginx -g 'daemon off;'"
    restart: always

  gabarito-api:
    container_name: gabarito-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/gabarito.db
    volumes:
      - gabaritoweb-db:/app/data
    command: sh -c "npx drizzle-kit push && npm run start"
    restart: always

volumes:
  gabaritoweb-db:
    driver: local
