services:
  gabarito-api:
    container_name: gabarito-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/gabarito.db
    volumes:
      - gabaritoweb-db:/app/data
    restart: always

volumes:
  gabaritoweb-db:
    driver: local
