services:
  gabarito-frontend-build:
    container_name: gabarito-frontend-build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/app/dist-out
    entrypoint: sh -c "rm -rf /app/dist-out/* && cp -rf /usr/share/nginx/html/. /app/dist-out/"
    restart: "no"

  gabarito-api:
    container_name: gabarito-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/gabarito.db
    volumes:
      - ./data/prod:/app/data:z
    restart: always
    depends_on:
      - gabarito-frontend-build
