services:
  backend:
    container_name: gabaritoweb-backend-dev
    user: "1000:1000"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data/dev:/app/data
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/gabarito.db
    env_file:
      - path: .env
        required: false

  frontend:
    container_name: gabaritoweb-frontend-dev
    user: "1000:1000"
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend
